# Generated by Django 4.1.1 on 2022-09-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_allbids_user_b_createl_user_l'),
    ]

    operations = [
        migrations.AddField(
            model_name='createl',
            name='ima',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
