# Generated by Django 4.1.1 on 2022-09-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='createl',
            name='status',
            field=models.CharField(default='active', max_length=64),
        ),
    ]
